const TRAKT_API_BASE = "https://api.trakt.tv";
const TMDB_API_BASE = "https://api.themoviedb.org/3";
const TMDB_IMAGE_BASE = "https://image.tmdb.org/t/p";

const TRAKT_CLIENT_ID = "f2b09c63e8841656e79fb32c0c7e843146b19d96bac5b3d2f82a6e4ff870ea96";
// Generated by encrypt-key.mjs
const TRAKT_ENCODED_KEY = {"salt":"klYpRInm/JtTWZc/zmwKcQ==","iv":"r2sUoMw2WNrYwXNm","data":"EFJEKXfoquT8dblEPRuw/zf05KqvjEf2QnynnE0xcT4/r9fAO4eegt51NYIRY84QjKG5oBxx/Ur0R3bP88BmNk8+6uELodb3+iSy1zxeNyk="};
const TMDB_ENCODED_KEY = {"salt":"0UwWowwSjsJMU4POKsV4Ig==","iv":"+bx/lXgl60BWzgFL","data":"5Gvc3sQEAjej4g9SmeU0lufPuU6jJZ/kDQZ8ojZd7u2KEY5Kzf5Lhr3WoyAIS0X0"};

let cached_trakt_secret_promise = Promise.resolve(null);
async function trakt_client_secret() {
  return await cached_trakt_secret_promise ||
	await (cached_trakt_secret_promise = decrypt_key(TRAKT_ENCODED_KEY));
}

let cached_tmdb_key_promise = Promise.resolve(null);
async function tmdb_api_key() {
  return await cached_tmdb_key_promise ||
    await (cached_tmdb_key_promise = decrypt_key(TMDB_ENCODED_KEY));
}

async function decrypt_key(encrypted_key) {
  const passphrase_key = 'easytv.passphrase';
  let passphrase = localStorage.getItem(passphrase_key);
  if (!passphrase) {
    passphrase = prompt('Enter site password:');
    if (!passphrase) return null;
  }
  try {
    const enc = new TextEncoder();
    const from_b64 = s => Uint8Array.from(atob(s), c => c.charCodeAt(0));
    const key_material = await crypto.subtle.importKey(
      'raw', enc.encode(passphrase), 'PBKDF2', false, ['deriveKey']);
    const key = await crypto.subtle.deriveKey(
      { name: 'PBKDF2', salt: from_b64(encrypted_key.salt), iterations: 100000, hash: 'SHA-256' },
      key_material, { name: 'AES-GCM', length: 256 }, false, ['decrypt']);
    const decrypted = await crypto.subtle.decrypt(
      { name: 'AES-GCM', iv: from_b64(encrypted_key.iv) },
      key, from_b64(encrypted_key.data));
    const decoded_key = new TextDecoder().decode(decrypted);
    localStorage.setItem(passphrase_key, passphrase);
    return decoded_key;
  } catch {
    localStorage.removeItem(passphrase_key);
    alert('Wrong passphrase');
    return null; // wrong passphrase
  }
}

async function tmdb_get(path) {
  const api_key = await tmdb_api_key();
  const separator = path.includes("?") ? "&" : "?";
  const response = await fetch(`${TMDB_API_BASE}${path}${separator}api_key=${api_key}`);
  if (!response.ok) throw new Error(`TMDB API error ${response.status}`);
  return response.json();
}

async function trakt_get(path, access_token) {
  const response = await fetch(`${TRAKT_API_BASE}${path}`, {
    headers: { "Content-Type": "application/json",
	       "Authorization": `Bearer ${access_token}`,
	       "trakt-api-version": "2",
	       "trakt-api-key": TRAKT_CLIENT_ID,
	     }
    
  });
  if (response.status === 401) throw new AuthError("Token expired or invalid");
  if (!response.ok) throw new Error(`Trakt API error ${response.status}`);
  return response.json();
}

async function trakt_post (path, params) {
  return await fetch(`${TRAKT_API_BASE}${path}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(params),
  });
}

class AuthError extends Error {};

let current_access_token = null;


// --- Auth / device flow ---

const trakt_access_token_key = "easytv.trakt_access_token";

async function start_device_flow() {
  const response = await trakt_post("/oauth/device/code", { client_id: TRAKT_CLIENT_ID });
  if (!response.ok) throw new Error("Failed to start device flow");
  return response.json();
}

async function poll_for_token(device_code, interval_seconds) {
  const client_secret = await trakt_client_secret();
  // TODO: just don't allow aborting trakt_client_secret to fail
  if (client_secret === null) throw new Error("Passphrase required to use this app");
  let poll_interval = (interval_seconds ?? 5) * 1000;
  while (true) {
    await new Promise(resolve => setTimeout(resolve, poll_interval));
    const response = await trakt_post("/oauth/device/token", {
      code: device_code,
      client_id: TRAKT_CLIENT_ID,
      client_secret: client_secret
    });
    if (response.status === 200) return response.json();
    // TODO: refresh it!!
    if (response.status === 410) throw new Error("Login code expired. Please try again.");
    if (response.status === 418) throw new Error("Authorization denied.");
    if (response.status === 429) { poll_interval *= 2; continue; }
    // 400 = pending, 409 = already used
    if (response.status === 400 || response.status === 409) continue;
    throw new Error(`Unexpected response ${response.status} while waiting for authorization`);
  }
}

function sort_title(title) {
  return title.replace(/^(A|The) /i, "");
}

// --- Rendering ---

function render_show_row(item) {
  const { show } = item;
  const unseen_count = (show.aired_episodes ?? 0) - item.watched_count;

  const row_div = document.createElement("div");
  row_div.className = "show-row";

  // Header (always visible, clickable)
  const header_div = document.createElement("div");
  header_div.className = "show-header";

  const poster_img = document.createElement("img");
  poster_img.className = "show-poster-thumb";
  poster_img.alt = show.title;

  const info_div = document.createElement("div");
  info_div.className = "show-info";

  const title_line = document.createElement("div");
  title_line.className = "show-title-line";
  title_line.textContent = show.title;

  const next_line = document.createElement("div");
  next_line.className = "show-next-line";
  next_line.textContent = `${unseen_count} episode${unseen_count !== 1 ? "s" : ""} left`;

  const network_line = document.createElement("div");
  network_line.className = "show-network-line";
  network_line.textContent = show.network ?? "";

  info_div.append(title_line, next_line, network_line);
  const meta_parts = [show.year, show.status].filter(Boolean);
  const meta_suffix = meta_parts.length ? ` (${meta_parts.join(", ")})` : "";
  const overview_text = (show.overview ?? "") + meta_suffix;
  if (overview_text) {
    const overview_line = document.createElement("div");
    overview_line.className = "show-overview-line";
    overview_line.textContent = overview_text;
    info_div.appendChild(overview_line);
  }
  header_div.append(poster_img, info_div);
  row_div.appendChild(header_div);

  // Expanded content
  const expanded_div = document.createElement("div");
  expanded_div.className = "show-expanded";
  expanded_div.hidden = true;
  row_div.appendChild(expanded_div);

  // Fetch progress eagerly — used for "Up next" and for expanding seasons
  const progress_promise = trakt_get(
    `/shows/${show.ids.trakt}/progress/watched?extended=full`,
    current_access_token
  ).then(progress => {
    if (progress.next_episode) {
      const ep = progress.next_episode;
      next_line.textContent = `Up next S${ep.season}E${ep.number} — ${unseen_count} episode${unseen_count !== 1 ? "s" : ""} left`;
    }
    return progress;
  }).catch(() => null);

  // Fetch poster eagerly
  if (show.ids.tmdb) {
    tmdb_get(`/tv/${show.ids.tmdb}`).then(tmdb => {
      if (tmdb.poster_path) {
        poster_img.src = `${TMDB_IMAGE_BASE}/w92${tmdb.poster_path}`;
      }
    }).catch(() => {});
  }

  // Click to expand/collapse
  let seasons_rendered = false;
  header_div.addEventListener("click", async () => {
    const opening = expanded_div.hidden;
    expanded_div.hidden = !opening;
    row_div.classList.toggle("open", opening);
    if (!expanded_div.hidden && !seasons_rendered) {
      seasons_rendered = true;
      const loading = document.createElement("div");
      loading.textContent = "Loading…";
      expanded_div.appendChild(loading);
      try {
        const progress = await progress_promise;
        loading.remove();
        if (progress) {
          for (const season of progress.seasons) {
            expanded_div.appendChild(render_season_row(season, show.ids.trakt));
          }
        }
      } catch (error) {
        loading.textContent = `Error loading progress: ${error.message}`;
      }
    }
  });

  return row_div;
}

function render_season_row(season, show_id) {
  const details = document.createElement("details");
  details.className = "season-row";

  const summary = document.createElement("summary");
  summary.className = "season-summary";
  const season_label = season.number === 0 ? "Specials" : `Season ${season.number}`;
  const unseen_count = season.aired - season.completed;
  if (unseen_count > 0) summary.style.fontWeight = "bold";
  const count_label = unseen_count > 0 ? ` (${season.completed} seen, ${unseen_count} unseen)` : "";
  summary.textContent = `${season_label}${count_label}`;
  details.appendChild(summary);

  const episodes_div = document.createElement("div");
  episodes_div.className = "episodes-list";
  details.appendChild(episodes_div);

  const completion_by_number = new Map(season.episodes.map(ep => [ep.number, ep]));
  let episodes_loaded = false;
  details.addEventListener("toggle", async () => {
    if (!details.open || episodes_loaded) return;
    episodes_loaded = true;
    episodes_div.textContent = "Loading…";
    try {
      const episode_details = await trakt_get(
        `/shows/${show_id}/seasons/${season.number}?extended=full`,
        current_access_token
      );
      episodes_div.textContent = "";
      for (const ep of episode_details) {
        const progress = completion_by_number.get(ep.number) ?? { completed: false };
        episodes_div.appendChild(render_episode_row({ ...progress, ...ep }));
      }
    } catch (error) {
      episodes_div.textContent = `Error loading episodes: ${error.message}`;
    }
  });

  return details;
}

function render_episode_row(episode) {
  const div = document.createElement("div");
  div.className = `episode-row ${episode.completed ? "watched" : "unwatched"}`;
  const ep_num = `E${String(episode.number).padStart(2, "0")}`;
  if (episode.overview) {
    const details = document.createElement("details");
    if (!episode.completed) details.open = true;
    const summary = document.createElement("summary");
    summary.className = "episode-summary";
    summary.style.color = episode.completed ? "#888" : "#000";
    summary.textContent = `${episode.completed ? "✓" : "○"} ${ep_num}${episode.title ? ` — ${episode.title}` : ""}`;
    const overview = document.createElement("div");
    overview.className = "episode-overview";
    overview.style.color = episode.completed ? "#888" : "#000";
    overview.textContent = episode.overview;
    details.append(summary, overview);
    div.appendChild(details);
  } else {
    div.textContent = `${episode.completed ? "✓" : "○"} ${ep_num}${episode.title ? ` — ${episode.title}` : ""}`;
  }
  return div;
}

// --- Views ---

function show_login_view() {
document.getElementById("login-section").hidden = false;
  document.getElementById("watchlist-section").hidden = true;
  document.getElementById("user-info").innerHTML = "";
  const code_el = document.getElementById("device-code-display");
  code_el.hidden = true;
  code_el.innerHTML = "";
}


function show_watchlist_view() {
  document.getElementById("login-section").hidden = true;
  document.getElementById("watchlist-section").hidden = false;
}

async function run_device_login() {
  const status_el = document.getElementById("login-status");
  const code_el = document.getElementById("device-code-display");
  const login_btn = document.getElementById("login-btn");

  login_btn.disabled = true;
  status_el.textContent = "Starting login…";
  status_el.className = "";
  code_el.hidden = true;

  try {
    const device = await start_device_flow();

    const popup_width = 520;
    const popup_height = 600;
    const popup_left = window.screenX + Math.round((window.outerWidth - popup_width) / 2);
    const popup_top = window.screenY + Math.round((window.outerHeight - popup_height) / 2);
    const auth_popup = window.open(device.verification_url, "trakt-auth",
      `width=${popup_width},height=${popup_height},left=${popup_left},top=${popup_top}`);

    navigator.clipboard.writeText(device.user_code).then(() => {
      const copied_span = document.createElement("span");
      copied_span.textContent = " [copied to clipboard]";
      code_el.appendChild(copied_span);
    }).catch(() => {});

    code_el.hidden = false;
    const code_strong = document.createElement("strong");
    code_strong.textContent = device.user_code;
    code_el.textContent = "Enter this code in the popup: ";
    code_el.appendChild(code_strong);
    status_el.textContent = "Waiting for authorization…";

    const token_data = await poll_for_token(device.device_code, device.interval);
    if (auth_popup && !auth_popup.closed) auth_popup.close();
    code_el.hidden = true;
    code_el.textContent = "";
    status_el.textContent = "";
    localStorage.setItem(trakt_access_token_key, token_data.access_token);
    await load_watchlist(token_data.access_token);
  } catch (error) {
    status_el.textContent = error.message;
    status_el.className = "error";
  } finally {
    login_btn.disabled = false;
  }
}

async function load_watchlist(access_token) {
  current_access_token = access_token;
  show_watchlist_view();
  const status_el = document.getElementById("watchlist-status");
  const grid_el = document.getElementById("shows-grid");

  status_el.textContent = "Loading…";
  grid_el.innerHTML = "";

  try {
    const [profile, watchlist_items, watched_items] = await Promise.all([
      trakt_get("/users/me", access_token),
      trakt_get("/users/me/watchlist/shows?extended=full", access_token),
      trakt_get("/users/me/watched/shows?extended=full", access_token),
    ]);

    const hidden_items = await trakt_get("/users/hidden/progress_watched?type=show&limit=1000", access_token)
      .catch(e => { console.warn("Hidden shows fetch failed:", e.message); return []; });
    const hidden_ids = new Set(hidden_items.map(item => item.show.ids.trakt));

    // Build union keyed by trakt show ID
    const shows_by_id = new Map();

    for (const item of watchlist_items) {
      shows_by_id.set(item.show.ids.trakt, {
        show: item.show,
        listed_at: item.listed_at,
        watched_count: 0,
      });
    }

    for (const item of watched_items) {
      const watched_count = item.seasons.reduce(
        (total, season) => total + season.episodes.length, 0
      );
      const existing = shows_by_id.get(item.show.ids.trakt);
      if (existing) {
        existing.watched_count = watched_count;
      } else {
        shows_by_id.set(item.show.ids.trakt, {
          show: item.show,
          listed_at: item.last_watched_at,
          watched_count,
        });
      }
    }

    // Only shows with unwatched aired episodes, sorted by title
    const shows = Array.from(shows_by_id.values())
      .filter(item => !hidden_ids.has(item.show.ids.trakt))
      .filter(item => (item.show.aired_episodes ?? 0) > item.watched_count)
      .sort((a, b) => sort_title(a.show.title).localeCompare(sort_title(b.show.title)));

    const logout_btn = document.createElement("button");
    logout_btn.id = "logout-btn";
    logout_btn.textContent = "Log out";
    logout_btn.addEventListener("click", () => {
      localStorage.removeItem(trakt_access_token_key);
      show_login_view();
    });

    const user_info_el = document.getElementById("user-info");
    user_info_el.textContent = profile.username + " ";
    user_info_el.appendChild(logout_btn);

    status_el.textContent = `${shows.length} show${shows.length !== 1 ? "s" : ""}`;
    for (const item of shows) {
      grid_el.appendChild(render_show_row(item));
    }
  } catch (error) {
    if (error instanceof AuthError) {
      localStorage.removeItem(trakt_access_token_key);
      show_login_view();
      document.getElementById("login-status").textContent = "Session expired. Please log in again.";
    } else {
      status_el.textContent = error.message;
      status_el.className = "error";
    }
  }
}

// --- Init ---

document.getElementById("login-btn").addEventListener("click", run_device_login);

const stored_token = localStorage.getItem(trakt_access_token_key);
if (stored_token) {
  load_watchlist(stored_token);
} else {
  show_login_view();
}
