const trakt = (() => {
  const TRAKT_API_BASE = "https://api.trakt.tv";
  const TRAKT_CLIENT_ID = "f2b09c63e8841656e79fb32c0c7e843146b19d96bac5b3d2f82a6e4ff870ea96";

  // Generated by encrypt-key.mjs
  const TRAKT_ENCODED_KEY = {"salt":"klYpRInm/JtTWZc/zmwKcQ==","iv":"r2sUoMw2WNrYwXNm","data":"EFJEKXfoquT8dblEPRuw/zf05KqvjEf2QnynnE0xcT4/r9fAO4eegt51NYIRY84QjKG5oBxx/Ur0R3bP88BmNk8+6uELodb3+iSy1zxeNyk="};

  const access_token_key = "easytv.trakt_access_token";
  const refresh_token_key = "easytv.trakt_refresh_token";

  let client_secret = null;

  async function init () {
    client_secret = await decrypt_key(TRAKT_ENCODED_KEY);
  }

  function access_token() {
    return localStorage.getItem(access_token_key);
  }

  function set_access_data(data) {
    if (data) {
      localStorage.setItem(access_token_key, data.access_token);
      localStorage.setItem(refresh_token_key, data.refresh_token);
    } else {
      localStorage.removeItem(access_token_key);
      localStorage.removeItem(refresh_token_key);
    }
  }

  async function trakt_post(path, params) {
    return fetch(`${TRAKT_API_BASE}${path}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(params),
    });
  }

  async function refresh_access_token() {
    const refresh_token = localStorage.getItem(refresh_token_key);
    if (!refresh_token) return;
    set_access_data(null);
    const response = await trakt_post("/oauth/token", {
      refresh_token,
      client_id: TRAKT_CLIENT_ID,
      client_secret,
      redirect_uri: "urn:ietf:wg:oauth:2.0:oob",
      grant_type: "refresh_token",
    });
    if (!response.ok) return;
    set_access_data(await response.json());
  }

  async function authed(method, path, params = null) {
    const do_request = () => {
      const token = access_token();
      if (!token) throw new Error("Trakt: not logged in");
      return fetch(`${TRAKT_API_BASE}${path}`, {
        method,
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${token}`,
          "trakt-api-version": "2",
          "trakt-api-key": TRAKT_CLIENT_ID,
        },
        body: params ? JSON.stringify(params) : undefined,
      });
    };
    let response = await do_request();
    if (response.status === 401) {
      await refresh_access_token();
      response = await do_request();
    }
    if (!response.ok) {
      const body = await response.text().catch(() => "");
      throw new Error(`Trakt API error ${response.status}: ${body}`);
    }
    if (response.status === 204) return null;
    return response.json();
  }

  // --- Notes ---

  const notes = (() => {
    const cache = new Map();
    let load_promise = null;

    function load_all() {
      if (!load_promise) {
        load_promise = authed("GET", "/users/me/notes/shows")
          .then(items => {
            for (const item of items) {
              cache.set(item.show.ids.trakt, { note_id: item.note.id, text: item.note.notes });
            }
          }).catch(() => {});
      }
      return load_promise;
    }

    return {
      load_all,
      reset() { cache.clear(); load_promise = null; },
      async get(show_id) {
        await load_all();
        return cache.get(show_id)?.text ?? "";
      },
      async set(show_id, text) {
        await load_all();
        const existing = cache.get(show_id);
        if (!text.trim()) {
          if (existing) {
            await authed("DELETE", `/notes/${existing.note_id}`);
            cache.delete(show_id);
          }
        } else if (existing) {
          await authed("PUT", `/notes/${existing.note_id}`, { notes: text });
          existing.text = text;
        } else {
          const result = await authed("POST", "/notes", {
            notes: text, show: { ids: { trakt: show_id } }
          });
          cache.set(show_id, { note_id: result.id, text });
        }
      },
    };
  })();

  // --- Auth flow ---

  async function get_login_data() {
    const response = await trakt_post("/oauth/device/code", { client_id: TRAKT_CLIENT_ID });
    if (!response.ok) throw new Error("Failed to start device flow");
    return response.json();
  }

  async function wait_for_login(device) {
    const device_code = device.device_code;
    const interval_seconds = device.interval;
    let poll_interval = (interval_seconds ?? 5) * 1000;
    while (true) {
      await new Promise(resolve => setTimeout(resolve, poll_interval));
      const response = await trakt_post("/oauth/device/token", {
        code: device_code,
        client_id: TRAKT_CLIENT_ID,
        client_secret,
      });
      switch (response.status) {
        case 200: {
          const token_data = await response.json();
          set_access_data(token_data);
          return token_data;
        }
        case 429: poll_interval *= 2; continue;
        case 400: case 409: continue;

        case 410: throw new Error("Login code expired. Please try again.");
        case 418: throw new Error("Authorization denied.");
        default: throw new Error(`Unexpected response ${response.status} while waiting for authorization`);
      }
    }
  }

  return {
    notes,
    init,
    get_login_data,
    wait_for_login,
    is_logged_in: () => !!access_token(),
    logout: () => set_access_data(null),


    get_profile:               () => authed("GET", "/users/me"),
    get_watchlist:             () => authed("GET", "/users/me/watchlist/shows?extended=full"),
    get_watched_shows:         () => authed("GET", "/users/me/watched/shows?extended=full"),
    get_hidden_shows:          () => authed("GET", "/users/hidden/progress_watched?type=show&limit=1000"),
    get_show_progress:         (show_id, extended = false) => authed("GET", `/shows/${show_id}/progress/watched${extended ? "?extended=full" : ""}`),
    get_season_episodes:       (show_id, season_number) => authed("GET", `/shows/${show_id}/seasons/${season_number}?extended=full`),
    mark_episode_watched:      (episode_id) => authed("POST", "/sync/history", { episodes: [{ ids: { trakt: episode_id } }] }),
    mark_episode_unwatched:    (episode_id) => authed("POST", "/sync/history/remove", { episodes: [{ ids: { trakt: episode_id } }] }),
  };
})();
